<a href="https://colab.research.google.com/github/young-ha713/test_visuallization/blob/main/python_language.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
np.__version__

'1.19.5'

In [ ]:
def onehotcylinder(cylinders):
  if cylinders == 3:
    cylinder = np.array([1,0,0,0,0])
  elif cylinders == 4:
    cylinder = np.array([0,1,0,0,0])
  elif cylinders == 5:
    cylinder = np.array([0,0,1,0,0])
  elif cylinders == 6:
    cylinder = np.array([0,0,0,1,0])
  else :
    cylinder = np.array([0,0,0,0,1])
  return cylinder

In [ ]:
onehotcylinder(4) , onehotcylinder(6)

(array([0, 1, 0, 0, 0]), array([0, 0, 0, 1, 0]))

In [ ]:
displacement = 307.0
horsepower = 130.0
weight = 3504.0
accel = 12.0
cylinders = 8
origin = 1
##if cylinders =8 ,origin =1 -->onehot encording
import numpy as np


x_continues =np.array([displacement, horsepower, weight, accel])
#cylinder =np.array([0,0,0,0,1]) #8
cylinder = onehotcylinder(cylinders)
org=np.array([1,0,0] )#1

In [ ]:
#np.concatenate((a, b), axis=None)
result =np.concatenate((x_continues, cylinder,org), axis=None)
result.shape, result

((12,),
 array([3.070e+02, 1.300e+02, 3.504e+03, 1.200e+01, 0.000e+00, 0.000e+00,
        0.000e+00, 0.000e+00, 1.000e+00, 1.000e+00, 0.000e+00, 0.000e+00]))

In [ ]:
type(x_continues), type(cylinder), type(org)

(numpy.ndarray, numpy.ndarray, numpy.ndarray)

In [ ]:
result =result.reshape(-1,result.size)
result,result.shape

(array([[3.070e+02, 1.300e+02, 3.504e+03, 1.200e+01, 0.000e+00, 0.000e+00,
         0.000e+00, 0.000e+00, 1.000e+00, 1.000e+00, 0.000e+00, 0.000e+00]]),
 (1, 12))

# function의 이해


In [ ]:
21+14


35

In [ ]:
32+45

77

In [ ]:
def sum():
  first=32
  second=45
  result =first+second
  return result

In [ ]:
sum()

77

In [ ]:
def sum(f01,s02):
  first=f01
  second=s02
  result =first+second
  return result,second,first

In [ ]:
r01,r02,r03=sum(32,21)
print(r01,r02)

53 21


In [ ]:
21*32*2

1344

In [ ]:
31*61*41

77531

In [ ]:
def nam(a,b,c):
  first=a
  sec=b
  third=c
  result=a*b*c
  return result

In [ ]:
nam(2,3,4)

24

In [ ]:
def diffparam(*var_list, **var_dict):
  print(var_dict)
  result01=len(var_list)
  return result01

In [ ]:
diffparam(1,2,3, a=2,b=3)

{'a': 2, 'b': 3}


3

In [ ]:
diffparam(1,2,3,5,6, c=5,d=6,a=2,b=3)

{'c': 5, 'd': 6, 'a': 2, 'b': 3}


5